# Generated by Django 5.0 on 2023-12-17 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id_user', models.AutoField(db_column='ID_User', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=100)),
                ('password', models.CharField(db_column='Password', max_length=100)),
            ],
            options={
                'db_table': 'App_User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id_candidate', models.AutoField(db_column='ID_Candidate', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Candidate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EducationalData',
            fields=[
                ('id_educational_data', models.AutoField(db_column='ID_Educational_Data', primary_key=True, serialize=False)),
                ('educational_institute', models.CharField(db_column='Educational_Institute', max_length=100)),
                ('receipt_date', models.DateField(db_column='Receipt_Date')),
                ('expiration_date', models.DateField(db_column='Expiration_Date')),
            ],
            options={
                'db_table': 'Educational_Data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dismissal',
            fields=[
                ('id_dismissal', models.AutoField(db_column='ID_Dismissal', primary_key=True, serialize=False)),
                ('reason', models.CharField(db_column='Reason', max_length=100)),
                ('dismissal_date', models.DateField(db_column='Dismissal_Date')),
                ('id_worker', models.IntegerField(db_column='ID_Worker')),
                ('id_place_of_work', models.IntegerField(db_column='ID_Place_Of_Work')),
                ('id_user', models.IntegerField(db_column='ID_User')),
                ('id_job_title', models.IntegerField(db_column='ID_Job_Title')),
                ('id_subdivision', models.IntegerField(db_column='ID_Subdivision')),
            ],
            options={
                'db_table': 'Dismissal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id_contract', models.AutoField(db_column='ID_Contract', primary_key=True, serialize=False)),
                ('receipt_date', models.DateField(db_column='Receipt_Date')),
                ('salary', models.BigIntegerField(db_column='Salary')),
                ('id_job_title', models.IntegerField(db_column='ID_Job_Title')),
                ('id_subdivision', models.IntegerField(db_column='ID_Subdivision')),
            ],
            options={
                'db_table': 'Employment_Contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobResume',
            fields=[
                ('id_job_resume', models.AutoField(db_column='ID_Job_Resume', primary_key=True, serialize=False)),
                ('surname', models.CharField(db_column='Surname', max_length=100)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('patronymic', models.CharField(blank=True, db_column='Patronymic', max_length=100, null=True)),
                ('gender', models.CharField(db_column='Gender', max_length=20)),
                ('phone_number', models.CharField(db_column='Phone_Number', max_length=20)),
                ('adress', models.CharField(db_column='Adress', max_length=200)),
                ('birthday', models.DateField(db_column='Birthday')),
                ('photo', models.BinaryField(blank=True, db_column='Photo', null=True)),
                ('position', models.CharField(db_column='Position', max_length=100)),
                ('work_experience', models.IntegerField(blank=True, db_column='Work_Experience', null=True)),
            ],
            options={
                'db_table': 'Job_Resume',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id_job_title', models.AutoField(db_column='ID_Job_Title', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'Job_Title',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceOfWork',
            fields=[
                ('id_place_of_work', models.AutoField(db_column='ID_Place_Of_Work', primary_key=True, serialize=False)),
                ('reseipt_date', models.DateField(db_column='Reseipt_Date')),
                ('expiration_date', models.DateField(blank=True, db_column='Expiration_Date', null=True)),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'Place_Of_Work',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id_recruitment', models.AutoField(db_column='ID_Recruitment', primary_key=True, serialize=False)),
                ('recruitment_date', models.DateField(db_column='Recruitment_Date')),
                ('id_worker', models.IntegerField(db_column='ID_Worker')),
                ('id_place_of_work', models.IntegerField(db_column='ID_Place_Of_Work')),
                ('id_user', models.IntegerField(db_column='ID_User')),
                ('id_job_title', models.IntegerField(db_column='ID_Job_Title')),
                ('id_subdivision', models.IntegerField(db_column='ID_Subdivision')),
            ],
            options={
                'db_table': 'Recruitment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.AutoField(db_column='ID_Role', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('canreadworkersdata', models.BooleanField(db_column='CanReadWorkersData')),
                ('caneditworkersdata', models.BooleanField(db_column='CanEditWorkersData')),
                ('canedituserdata', models.BooleanField(db_column='CanEditUserData')),
                ('candoorders', models.BooleanField(db_column='CanDoOrders')),
            ],
            options={
                'db_table': 'Role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SickLeave',
            fields=[
                ('id_sick_leave', models.AutoField(db_column='ID_Sick_Leave', primary_key=True, serialize=False)),
                ('receipt_date', models.DateField(db_column='Receipt_Date')),
                ('expiration_date', models.DateField(db_column='Expiration_Date')),
            ],
            options={
                'db_table': 'Sick_Leave',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StructuralSubdivision',
            fields=[
                ('id_subdivision', models.AutoField(db_column='ID_Subdivision', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'Structural_Subdivision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id_vacation', models.AutoField(db_column='ID_Vacation', primary_key=True, serialize=False)),
                ('receipt_date', models.DateField(db_column='Receipt_Date')),
                ('expiration_date', models.DateField(db_column='Expiration_Date')),
                ('id_user', models.IntegerField(db_column='ID_User')),
            ],
            options={
                'db_table': 'Vacation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VacationType',
            fields=[
                ('id_vacation_type', models.AutoField(db_column='ID_Vacation_Type', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'Vacation_Type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id_worker', models.AutoField(db_column='ID_Worker', primary_key=True, serialize=False)),
                ('surname', models.CharField(db_column='Surname', max_length=100)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('patronymic', models.CharField(blank=True, db_column='Patronymic', max_length=100, null=True)),
                ('gender', models.CharField(db_column='Gender', max_length=20)),
                ('birthday', models.DateField(db_column='Birthday')),
                ('work_experience', models.CharField(db_column='Work_Experience', max_length=100)),
                ('adress', models.CharField(db_column='Adress', max_length=200)),
                ('phone_number', models.CharField(db_column='Phone_Number', max_length=20)),
                ('photo', models.BinaryField(blank=True, db_column='Photo', null=True)),
            ],
            options={
                'db_table': 'Worker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id_order', models.AutoField(db_column='ID_Order', primary_key=True, serialize=False)),
                ('order_number', models.BigIntegerField(db_column='Order_Number')),
                ('receipt_date', models.DateField(db_column='Receipt_Date')),
            ],
            options={
                'db_table': 'Work_Order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Candidateplaceofwork',
            fields=[
                ('id_candidate', models.OneToOneField(db_column='ID_Candidate', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.candidate')),
                ('id_job_title', models.IntegerField(db_column='ID_Job_Title')),
                ('id_subdivision', models.IntegerField(db_column='ID_Subdivision')),
            ],
            options={
                'db_table': 'CandidatePlaceOfWork',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Candidateeducation',
            fields=[
                ('id_educational_data', models.OneToOneField(db_column='ID_Educational_Data', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.educationaldata')),
            ],
            options={
                'db_table': 'CandidateEducation',
                'managed': False,
            },
        ),
    ]
