# Generated by Django 5.0 on 2023-12-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='candidateeducation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='candidateplaceofwork',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dismissal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='educationaldata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employmentcontract',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jobresume',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jobtitle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='placeofwork',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recruitment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sickleave',
            options={},
        ),
        migrations.AlterModelOptions(
            name='structuralsubdivision',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vacation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vacationtype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={},
        ),
    ]
