# Generated by Django 5.0 on 2023-12-18 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_appuser_options_alter_candidate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.CharField(blank=True, db_column='Photo', null=True),
        ),



    ]
