# Generated by Django 5.0 on 2023-12-18 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_appuser_id_candidate_appuser_id_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='id_candidate',
            field=models.ForeignKey(blank=True, db_column='ID_Candidate', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.candidate'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='id_role',
            field=models.ForeignKey(db_column='ID_Role', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='id_worker',
            field=models.ForeignKey(blank=True, db_column='ID_Worker', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.worker'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='id_job_resume',
            field=models.ForeignKey(blank=True, db_column='ID_Job_Resume', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.jobresume'),
        ),
        migrations.AddField(
            model_name='candidateeducation',
            name='id_candidate',
            field=models.ForeignKey(db_column='ID_Candidate', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.candidate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidateplaceofwork',
            name='id_place_of_work',
            field=models.ForeignKey(db_column='ID_Place_Of_Work', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.placeofwork'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dismissal',
            name='id_contract',
            field=models.ForeignKey(db_column='ID_Contract', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.employmentcontract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dismissal',
            name='id_order',
            field=models.ForeignKey(db_column='ID_Order', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.workorder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='id_place_of_work',
            field=models.ForeignKey(db_column='ID_Place_Of_Work', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.placeofwork'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='id_worker',
            field=models.ForeignKey(db_column='ID_Worker', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.worker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeofwork',
            name='id_job_title',
            field=models.ForeignKey(db_column='ID_Job_Title', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.jobtitle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeofwork',
            name='id_subdivision',
            field=models.ForeignKey(db_column='ID_Subdivision', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.structuralsubdivision'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruitment',
            name='id_contract',
            field=models.ForeignKey(db_column='ID_Contract', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.employmentcontract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruitment',
            name='id_order',
            field=models.ForeignKey(db_column='ID_Order', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.workorder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sickleave',
            name='id_worker',
            field=models.ForeignKey(db_column='ID_Worker', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.worker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacation',
            name='id_order',
            field=models.ForeignKey(db_column='ID_Order', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.workorder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacation',
            name='id_vacationtype',
            field=models.ForeignKey(db_column='ID_VacationType', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.vacationtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacation',
            name='id_worker',
            field=models.ForeignKey(db_column='ID_Worker', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.worker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='id_user',
            field=models.ForeignKey(db_column='ID_User', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.appuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobresume',
            name='photo',
            field=models.CharField(blank=True, db_column='Photo', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.CharField(blank=True, db_column='Photo', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='candidateeducation',
            unique_together={('id_educational_data', 'id_candidate')},
        ),
        migrations.AlterUniqueTogether(
            name='candidateplaceofwork',
            unique_together={('id_candidate', 'id_place_of_work', 'id_job_title', 'id_subdivision')},
        ),
        migrations.AlterUniqueTogether(
            name='dismissal',
            unique_together={('id_dismissal', 'id_contract', 'id_worker', 'id_place_of_work', 'id_order', 'id_user', 'id_job_title', 'id_subdivision')},
        ),
        migrations.AlterUniqueTogether(
            name='employmentcontract',
            unique_together={('id_contract', 'id_worker', 'id_place_of_work', 'id_job_title', 'id_subdivision')},
        ),
        migrations.AlterUniqueTogether(
            name='placeofwork',
            unique_together={('id_place_of_work', 'id_job_title', 'id_subdivision')},
        ),
        migrations.AlterUniqueTogether(
            name='recruitment',
            unique_together={('id_recruitment', 'id_contract', 'id_worker', 'id_place_of_work', 'id_order', 'id_user', 'id_job_title', 'id_subdivision')},
        ),
        migrations.AlterUniqueTogether(
            name='sickleave',
            unique_together={('id_sick_leave', 'id_worker')},
        ),
        migrations.AlterUniqueTogether(
            name='vacation',
            unique_together={('id_vacation', 'id_vacationtype', 'id_worker', 'id_order', 'id_user')},
        ),
        migrations.AlterUniqueTogether(
            name='workorder',
            unique_together={('id_order', 'id_user')},
        ),
    ]
