# Generated by Django 5.0 on 2023-12-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_appuser_id_candidate_appuser_id_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobresume',
            name='photo',
            field=models.CharField(blank=True, db_column='Photo', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.CharField(blank=True, db_column='Photo', max_length=50, null=True),
        ),
    ]
