# Generated by Django 5.0 on 2023-12-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_jobresume_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobresume',
            name='photo',
            field=models.ImageField(blank=True, db_column='Photo', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(blank=True, db_column='Photo', null=True, upload_to='uploads/'),
        ),
    ]
