# Generated by Django 5.0 on 2023-12-23 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_appuser_managers_appuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentcontract',
            name='id_job_title',
            field=models.ForeignKey(db_column='ID_Job_Title', on_delete=django.db.models.deletion.DO_NOTHING, to='main.jobtitle'),
        ),
        migrations.AlterField(
            model_name='employmentcontract',
            name='id_subdivision',
            field=models.ForeignKey(db_column='ID_Subdivision', on_delete=django.db.models.deletion.DO_NOTHING, to='main.structuralsubdivision'),
        ),
    ]
