# Generated by Django 5.0 on 2023-12-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_employmentcontract_id_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobresume',
            name='subdivision',
            field=models.CharField(db_column='Subdivision', default='', max_length=100),
            preserve_default=False,
        ),
    ]
