# Generated by Django 5.0 on 2023-12-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_jobresume_subdivision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobresume',
            name='subdivision',
        ),
    ]
