# Generated by Django 5.0 on 2023-12-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_jobresume_subdivision'),
    ]

    operations = [
        migrations.AddField(
            model_name='dismissal',
            name='file',
            field=models.FileField(blank=True, db_column='File', null=True, upload_to='orders/'),
        ),
    ]
