# Generated by Django 5.0 on 2023-12-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_dismissal_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='file',
            field=models.FileField(blank=True, db_column='File', null=True, upload_to='orders/'),
        ),
        migrations.AddField(
            model_name='vacation',
            name='file',
            field=models.FileField(blank=True, db_column='File', null=True, upload_to='orders/'),
        ),
    ]
